config/routes.rb
Rails.application.routes.draw do

root "links#home" , as: :root
get 'links/new' => 'links#new', as: :new_link
post 'links/:id/upvote' => 'links#upvote', as: :upvote_link
post 'links' => 'links#create', as: :links
post 'links/:id/downvote' => 'links#downvote', as: :downvote_link
resources :links do
  member do
    post 'upvote'
  end
end

end

app/models/link.rb
class Link < ActiveRecord::Base
  validates :url, presence: true
  validates :title, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def home
  @links = Link.all.order("vote_count desc")
  end

def new
@link = Link.new
end

def detail
    @link = Link.find params[:id]
  end

  def create
    @link = Link.new(link_params)
  if @link.save
    redirect_to root_path
  else
    render :new
  end
  end



def upvote
  @link = Link.find params[:id]
 @link.update vote_count: (@link.vote_count + 1)
  redirect_to root_path

end

def downvote
  @link = Link.find params[:id]
 @link.update vote_count: (@link.vote_count - 1)
  redirect_to root_path
  end

def link_params
  params.require(:link).permit(:title, :url, :created_at, :photo, :id)
end


def hot

end

  def rising

  end

  def controversial

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reddit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/links/home.html.erb
<div class= "container">
  <h1> Fake Reddit </h1>

<%= link_to new_link_path do %>
  <i class="fa fa-plus"></i>Add New Link
<% end %>
<div class="content"
  <% @links.each do |link| %>
<div class="media">
  <div class = "media-left">
  <%= link_to upvote_link_path(link.id), method: :post, class:"btn counter-button" do%>
  <i class= "fa fa-thumbs-o-up"></i>
    <% end %>
  <%= link.vote_count %>
  <%= link_to downvote_link_path(link.id), method: :post, class:"btn counter-button" do%>
  <i class= "fa fa-thumbs-o-down"></i>
  <% end %>
</div>
  <div class="media-left media-middle">
    <%= image_tag(link.picture, class:"media-object") %>
  </div>
  <div class="media-body">
    <%= link_to "http://#{link.url}" do %>
    <h4 class="media-heading"><%=link.title%></h4>
    <% end %>
    <small>Published <%= distance_of_time_in_words_to_now link.created_at %> ago. </small>
  </div>

  </div>
  <% end %>
</div>
</div>

app/views/links/new.html.erb
<div class= "container">
<%= simple_form_for @link do |l| %>
  <%= l.input :url, error: 'Url is mandatory, please specify one' %>
  <%= l.input :title,  error: "Title is mandatory" %>
  <%= l.input :picture %>
  <%= l.submit 'Save', class:'btn btn-primary btn-lg' %>
<% end %>
</div>